packages:
  - packages/*

onlyBuiltDependencies:
  - better-sqlite3


catalog:
  "@nuxt/eslint": "latest"
  "eslint": "^9.39.1"
  "nuxt": "^4.2.1"
  "typescript": "^5.9.3"
  "vue": "^3.5.24"
  "@nuxtjs/i18n": "^10.2.0"
  "mjml": "^4.16.1"
  "@types/mjml": "^4.7.4"
  "drizzle-orm": "^0.44.7"
  "@libsql/client": "^0.15.15"
  "drizzle-kit": "^0.31.6"
  "better-auth": "^1.3.34"
  "better-sqlite3": "^12.4.1"
  "nuxt-auth-utils": "^0.5.25"
  "sass": "^1.94.0"
  "zod-to-json-schema": "^3.24.6"
  "@nuxt/content": "^3.8.0"
  "@nuxtjs/seo": "^3.2.2"
  "zod": "^4.1.12"
  "@huggingface/transformers": "3.7.6"
  "fabric": "^6.9.0"
  "vue-router": "^4.6.3"
  "nuxt-file-storage": "^0.3.0"
  "@atproto/api": "^0.18.0"
  "@fullcalendar/daygrid": "^6.1.19"
  "@fullcalendar/interaction": "^6.1.19"
  "@fullcalendar/list": "^6.1.19"
  "@fullcalendar/multimonth": "^6.1.19"
  "@fullcalendar/scrollgrid": "^6.1.19"
  "@fullcalendar/timegrid": "^6.1.19"
  "axios": "^1.13.2"
  "dayjs": "^1.11.19"
  "sharp": "^0.34.5"
  "@fullcalendar/core": "^6.1.19"
  "@fullcalendar/vue3": "^6.1.19"
  "@nuxt/fonts": "^0.12.1"
  "@types/three": "^0.181.0"
  "three": "^0.181.1"
  "@nuxt/image": "2.0.0"
  "@nuxt/scripts": "0.13.0"
  "@nuxt/test-utils": "3.20.1"
  "@nuxt/ui": "4.1.0"
  "@unhead/vue": "^2.0.19"
  "@vueuse/core": "14.0.0"
  "@vueuse/motion": "3.0.3"
  "@vueuse/nuxt": "14.0.0"
  "echarts": "^6.0.0"
  "@nuxt/hints": "1.0.0-alpha.1"
  
